---
# yamllint configuration
# See: https://yamllint.readthedocs.io/en/stable/configuration.html

extends: default

rules:
  # Disable line length check
  line-length: disable

  # Allow truthy values (useful for GitHub Actions)
  truthy:
    allowed-values: ['true', 'false', 'on', 'off', 'yes', 'no']
    check-keys: false
    level: warning

  # Be more flexible with comments
  comments:
    min-spaces-from-content: 1

  # Allow empty values
  empty-values:
    forbid-in-block-mappings: false
    forbid-in-flow-mappings: false

ignore: |
  secrets/sops/secrets.sops.yaml
  secrets/sops/*.sops.yaml
  .github/workflows/ci.yml
  flake.lock
