[formatter.alejandra]
command = "alejandra"
includes = ["*.nix"]

[formatter.deadnix]
command = "deadnix"
options = ["--edit"]
includes = ["*.nix"]

# Shell formatting disabled due to conflicts
# [formatter.shellcheck]
# command = "shellcheck"
# includes = ["*.sh"]

# [formatter.shfmt]
# command = "shfmt"
# options = ["-w"]
# includes = ["*.sh"]

[formatter.taplo]
command = "taplo"
options = ["format"]
includes = ["*.toml"]

[global]
excludes = [".git-crypt/*", "secrets/*", "flake.lock"]
