_: {
  sops = {
    age = {
      keyFile = "/var/lib/sops-nix/keys/age/keys.txt"; # generated by scripts/init-secrets.sh
      generateKey = false;
    };
    defaultSopsFile = ./secrets.sops.yaml;
    validateSopsFiles = false; # keep flexible for initial bootstrap
    secrets = {
      # Backups
      RESTIC_PASSWORD = {};
      B2_ACCOUNT_ID = {};
      B2_ACCOUNT_KEY = {};

      # Tailscale join
      TAILSCALE_AUTHKEY = {};

      # Optional tokens
      MOTHERDUCK_TOKEN = {};
      GITHUB_TOKEN = {};
      GHCR_USER = {};
      GHCR_TOKEN = {};

      # Cachix private cache authentication
      CACHIX_AUTH_TOKEN = {};
      CACHIX_SIGNING_KEY = {};

      # Runtime envfile to drive restic (constructed by sops; see README)
      restic_env = {
        name = "restic_env";
        path = "/run/secrets/restic_env";
      };
    };
  };

  # Expose restic env from sops secret
  systemd.tmpfiles.rules = [
    "f /run/secrets/restic_env 0600 root root -"
  ];
}
