{ config, lib, pkgs, ... }:
{
  # CPU microcode
  hardware.cpu.amd.updateMicrocode = true;

  # Host platform hints
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  # Basic hardware things commonly generated by nixos-generate-config can be slim here;
  # disko will populate fileSystems via enableConfig.
  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "ahci" "usbhid" ];
  boot.kernelModules = [ "kvm-amd" ];
}
