name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

# SECURITY: Minimal permissions, explicit per-job
permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # SECURITY: Secure Nix evaluation
  NIX_CONFIG: |
    extra-experimental-features = nix-command flakes
    sandbox = true
    max-jobs = auto

jobs:
  # Combined flake validation and basic checks
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
      security-events: write
    outputs:
      config-exists: ${{ steps.check-config.outputs.exists }}
      has-checks: ${{ steps.check-config.outputs.has-checks }}
      has-blazar: ${{ steps.check-config.outputs.has-blazar }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Install Determinate Nix
        uses: DeterminateSystems/determinate-nix-action@a7e500c712ad97316904566d98013596e868d2fb # v3.11.1

      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@87b14cf437d03d37989d87f0fa5ce4f5dc1a330b # v8

      # SECURITY: Enhanced flake health check
      - name: Check flake health
        uses: DeterminateSystems/flake-checker-action@078f5f7f47ee188aa6cb472527ca5984e195222d # v9
        with:
          fail-mode: true

      - name: Validate flake structure
        id: check-config
        run: |
          echo "🔍 Validating flake and configuration..."
          
          # Check flake validity
          if ! nix flake check --show-trace --accept-flake-config; then
            echo "❌ Flake check failed"
            exit 1
          fi
          
          # Robustly detect NixOS configurations without forcing full evaluation
          has_configs=$(nix eval --raw --expr 'builtins.hasAttr "nixosConfigurations" (builtins.getFlake ".")' || echo false)
          if [[ "$has_configs" == "true" ]]; then
            echo "config-exists=true" >> "$GITHUB_OUTPUT"
            echo "✅ NixOS configurations found"
            echo "Available configs:"
            nix eval --json --expr '(builtins.attrNames (builtins.getFlake ".").nixosConfigurations)' | nix run nixpkgs#jq -- -r '.[]' || true
          else
            echo "config-exists=false" >> "$GITHUB_OUTPUT"
            echo "ℹ️ No NixOS configurations found"
          fi
          
          # Check for validation targets
          if nix eval --json .#checks.x86_64-linux >/dev/null 2>&1; then
            echo "has-checks=true" >> "$GITHUB_OUTPUT"
            echo "✅ Validation checks available"
          else
            echo "has-checks=false" >> "$GITHUB_OUTPUT"
            echo "ℹ️ No validation checks found"
          fi
          
          # Check for blazar host configuration
          has_blazar=$(nix eval --raw --expr 'builtins.hasAttr "blazar" (builtins.getFlake ".").nixosConfigurations' || echo false)
          echo "has-blazar=$has_blazar" >> "$GITHUB_OUTPUT"
          if [[ "$has_blazar" == "true" ]]; then
            echo "✅ Blazar host configuration found"
          else
            echo "ℹ️ No blazar host configuration found"
          fi

      # SECURITY: Validate dependencies and inputs
      - name: Security validation
        run: |
          echo "🔒 Running security validation..."
          set -euo pipefail
          # Ensure jq is available via Nix
          if ! command -v jq >/dev/null 2>&1; then
            jq() { nix run nixpkgs#jq -- "$@"; }
          fi
          
          # Check for unsafe Nix features (fail only on allowBroken/allowInsecure)
          if grep -R --include="*.nix" -nE "allowBroken|allowInsecure" . --exclude-dir=".git" 2>/dev/null; then
            echo "⚠️ Unsafe Nix features detected (allowBroken/allowInsecure)"
            exit 1
          fi
          # Note: allowUnfree is acceptable for systems needing proprietary software
          if grep -R --include="*.nix" -nE "allowUnfree" . --exclude-dir=".git" >/dev/null; then
            echo "ℹ️ allowUnfree detected (acceptable for proprietary software support)"
          fi
          
          # Validate flake inputs are from trusted sources  
          nix flake metadata --json > flake-meta.json
          untrusted_count=0
          while read -r owner repo; do
            case "$owner" in
              NixOS|nix-community|cachix|numtide|hercules-ci|Mic92|nlewo|rrbutani|edolstra) 
                echo "✅ Trusted: $owner/$repo" ;;
              *)
                echo "⚠️ Untrusted: $owner/$repo"
                ((untrusted_count++)) ;;
            esac
          done < <(nix run nixpkgs#jq -- -r '.locks.nodes[] | select(.original.owner) | "\(.original.owner) \(.original.repo)"' flake-meta.json)
          
          if [[ $untrusted_count -gt 0 ]]; then
            echo "❌ $untrusted_count untrusted inputs found"
            exit 1
          fi
          
          echo "✅ All security checks passed"

  # Code quality and formatting
  code-quality:
    runs-on: ubuntu-latest
    needs: validate
    timeout-minutes: 15
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Install Determinate Nix
        uses: DeterminateSystems/determinate-nix-action@a7e500c712ad97316904566d98013596e868d2fb # v3.11.1

      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@87b14cf437d03d37989d87f0fa5ce4f5dc1a330b # v8

      - name: Setup devenv cache
        uses: cachix/cachix-action@18cf96c7c98e048e10a83abd92116114cd8504be # v14
        with:
          name: devenv

      - name: Install devenv
        run: nix profile install nixpkgs#devenv

      # IMPROVED: Enhanced formatting checks
      - name: Check code formatting
        run: |
          echo "🎨 Checking code formatting..."
          
          # Try treefmt first (modern approach)
          if nix build .#formatter --show-trace 2>/dev/null; then
            echo "Using treefmt formatter"
            if ! ./result/bin/treefmt --check --no-cache .; then
              echo "❌ Code formatting issues found. Run 'nix fmt' to fix."
              exit 1
            fi
          else
            echo "Using alejandra fallback"
            if ! nix run nixpkgs#alejandra -- --check .; then
              echo "❌ Code formatting issues found. Run 'nix run nixpkgs#alejandra -- .' to fix."
              exit 1
            fi
          fi

      - name: Lint Nix code
        run: |
          echo "🔍 Running Nix linters..."
          
          # Check for dead code
          if command -v deadnix >/dev/null 2>&1; then
            deadnix --fail --exclude flake.nix .
          else
            nix run nixpkgs#deadnix -- --fail --exclude flake.nix .
          fi
          
          # Static analysis
          if command -v statix >/dev/null 2>&1; then
            statix check .
          else
            nix run nixpkgs#statix -- check .
          fi

      # ENHANCED: Better shell script checking
      - name: Check shell scripts
        run: |
          echo "🐚 Checking shell scripts..."
          
          shopt -s globstar nullglob
          scripts=(**/*.sh **/scripts/* **/**/scripts/*)
          
          if [[ ${#scripts[@]} -gt 0 ]]; then
            # Check syntax and style
            nix run nixpkgs#shellcheck -- "${scripts[@]}"
            nix run nixpkgs#shfmt -- -d "${scripts[@]}"
            echo "✅ All shell scripts passed checks"
          else
            echo "ℹ️ No shell scripts found"
          fi

      # ENHANCED: Document validation
      - name: Validate documentation
        run: |
          echo "📚 Validating documentation..."
          
          # Check markdown files
          if find . -name "*.md" -not -path "./.git/*" | head -1 | read -r; then
            find . -name "*.md" -not -path "./.git/*" -exec nix run nixpkgs#markdownlint-cli -- {} +
          fi
          
          # Check YAML files
          if find . -name "*.yml" -o -name "*.yaml" -not -path "./.git/*" | head -1 | read -r; then
            nix run nixpkgs#yamllint -- .
          fi

      # ENHANCED: GitHub Actions validation
      - name: Validate GitHub Actions
        if: hashFiles('.github/workflows/*.yml', '.github/workflows/*.yaml') != ''
        run: |
          echo "⚙️ Validating GitHub Actions..."
          nix run nixpkgs#actionlint

      # DEVENV: Test development environments
      - name: Test devenv shells
        run: |
          echo "🧪 Testing devenv development environments..."
          
          # Test that devenv can build the shells
          echo "Testing default shell..."
          if nix develop --no-pure-eval --command echo "Default shell works"; then
            echo "✅ Default shell builds successfully"
          else
            echo "❌ Default shell failed to build"
            exit 1
          fi
          
          # Test language-specific shells
          for shell in python rust zig julia; do
            echo "Testing $shell shell..."
            if timeout 60 nix develop --no-pure-eval .#$shell --command echo "$shell shell works"; then
              echo "✅ $shell shell builds successfully"
            else
              echo "❌ $shell shell failed to build"
              exit 1
            fi
          done
          
          # Test devenv CLI integration
          echo "Testing devenv CLI..."
          if devenv test; then
            echo "✅ devenv test passed"
          else
            echo "❌ devenv test failed"
            exit 1
          fi

  # Build validation
  build-validation:
    runs-on: ubuntu-latest
    needs: validate
    if: needs.validate.outputs.config-exists == 'true' && needs.validate.outputs.has-blazar == 'true'
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Install Determinate Nix
        uses: DeterminateSystems/determinate-nix-action@a7e500c712ad97316904566d98013596e868d2fb # v3.11.1

      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@87b14cf437d03d37989d87f0fa5ce4f5dc1a330b # v8

      - name: Setup devenv cache
        uses: cachix/cachix-action@18cf96c7c98e048e10a83abd92116114cd8504be # v14
        with:
          name: devenv

      - name: Install devenv
        run: nix profile install nixpkgs#devenv

      - name: Build NixOS configuration
        run: |
          echo "🏗️ Building NixOS configuration..."
          
          # Build system configuration with security restrictions
          nix build \
            .#nixosConfigurations.blazar.config.system.build.toplevel \
            --show-trace \
            --option sandbox true \
            --option max-silent-time 600 \
            --option timeout 1800
          
          echo "✅ System configuration built successfully"
          
          # Show build info
          nix path-info --json result | nix run nixpkgs#jq -- -r '.[] | "Size: \(.narSize) bytes"'

  # Enhanced checks execution
  checks:
    runs-on: ubuntu-latest
    needs: validate
    if: needs.validate.outputs.has-checks == 'true'
    timeout-minutes: 20
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Install Determinate Nix
        uses: DeterminateSystems/determinate-nix-action@a7e500c712ad97316904566d98013596e868d2fb # v3.11.1

      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@87b14cf437d03d37989d87f0fa5ce4f5dc1a330b # v8

      - name: Setup devenv cache
        uses: cachix/cachix-action@18cf96c7c98e048e10a83abd92116114cd8504be # v14
        with:
          name: devenv

      - name: Install devenv
        run: nix profile install nixpkgs#devenv

      - name: Run validation checks
        run: |
          echo "✅ Running validation checks..."
          
          # Run all available checks
          nix build .#checks.x86_64-linux --show-trace
          
          echo "✅ All checks passed"

  # Security audit
  security-audit:
    runs-on: ubuntu-latest
    needs: validate
    if: needs.validate.outputs.config-exists == 'true' && needs.validate.outputs.has-blazar == 'true'
    timeout-minutes: 15
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Install Determinate Nix
        uses: DeterminateSystems/determinate-nix-action@a7e500c712ad97316904566d98013596e868d2fb # v3.11.1

      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@87b14cf437d03d37989d87f0fa5ce4f5dc1a330b # v8

      - name: Quick security scan
        run: |
          echo "🔍 Running security scan..."
          
          # Build system for scanning
          nix build .#nixosConfigurations.blazar.config.system.build.toplevel
          system_path=$(readlink -f result)
          
          # Quick vulnerability check
          if command -v vulnix >/dev/null 2>&1; then
            vulnix --system x86_64-linux "$system_path" || echo "⚠️ Vulnerabilities found (non-blocking in CI)"
          else
            nix run nixpkgs#vulnix -- --system x86_64-linux "$system_path" || echo "⚠️ Vulnerabilities found (non-blocking in CI)"
          fi

  # CI summary
  ci-summary:
    runs-on: ubuntu-latest
    needs: [validate, code-quality, build-validation, checks, security-audit]
    if: always()
    permissions:
      contents: read
    steps:
      - name: Generate CI summary
        run: |
          {
            echo "# 🎯 CI Pipeline Summary"
            echo ""
            echo "## Validation Results"
            echo "- **Flake validation**: ${{ needs.validate.result == 'success' && '✅ Passed' || '❌ Failed' }}"
            echo "- **Code quality**: ${{ needs.code-quality.result == 'success' && '✅ Passed' || needs.code-quality.result == 'skipped' && '⏭️ Skipped' || '❌ Failed' }}"
            echo "- **Build validation**: ${{ needs.build-validation.result == 'success' && '✅ Passed' || needs.build-validation.result == 'skipped' && '⏭️ Skipped' || '❌ Failed' }}"
            echo "- **Checks**: ${{ needs.checks.result == 'success' && '✅ Passed' || needs.checks.result == 'skipped' && '⏭️ Skipped' || '❌ Failed' }}"
            echo "- **Security audit**: ${{ needs.security-audit.result == 'success' && '✅ Passed' || needs.security-audit.result == 'skipped' && '⏭️ Skipped' || '❌ Failed' }}"
            echo ""
            echo "## Security Features"
            echo "- ✅ SHA-pinned actions (supply chain security)"
            echo "- ✅ Secure runner configuration"
            echo "- ✅ Minimal permissions (RBAC)"
            echo "- ✅ Sandboxed Nix builds"
            echo "- ✅ Dependency validation"
            echo "- ✅ Vulnerability scanning"
            echo ""
            if [[ "${{ needs.validate.result }}" == "success" && "${{ needs.code-quality.result }}" == "success" && ("${{ needs.build-validation.result }}" == "success" || "${{ needs.build-validation.result }}" == "skipped") ]]; then
              echo "🎉 **Overall Status**: All critical checks passed!"
            else
              echo "⚠️ **Overall Status**: Some checks failed - review required"
            fi
            echo ""
            echo "---"
            echo "*Hardened CI pipeline following 2025 security best practices*"
          } >> "$GITHUB_STEP_SUMMARY"
