name: CI

on:
  push:
    branches: [ main ]
  pull_request:

# Cancel previous runs if a new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  flake-check:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          install_url: https://releases.nixos.org/nix/nix-2.31.0/install
          extra_nix_config: |
            experimental-features = nix-command flakes
            substituters = https://cache.nixos.org/ https://nix-community.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=

      - name: Check flake
        run: nix flake check --show-trace

      - name: Build NixOS configuration
        run: nix build .#nixosConfigurations.blazar.config.system.build.toplevel --show-trace

  code-quality:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          install_url: https://releases.nixos.org/nix/nix-2.31.0/install
          extra_nix_config: |
            experimental-features = nix-command flakes
            substituters = https://cache.nixos.org/ https://nix-community.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=

      - name: Check code formatting (treefmt)
        run: nix develop --command treefmt --check

      - name: Check code formatting (alejandra fallback)
        run: nix develop --command alejandra --check .

      - name: Check for dead code
        run: nix develop --command deadnix --fail --exclude flake.nix .

      - name: Run static analysis
        run: nix develop --command statix check .

      - name: Check shell scripts
        run: nix develop --command shellcheck scripts/*.sh

      - name: Check shell script formatting
        run: nix develop --command shfmt -d scripts/*.sh

      - name: Lint Markdown files
        run: nix develop --command markdownlint *.md

      - name: Lint YAML files
        run: nix develop --command yamllint .

      - name: Lint GitHub Actions
        run: nix develop --command actionlint
