name: System Tests

on:
  pull_request:
    paths:
      - 'tests/**'
      - 'modules/**'
      - 'hosts/**'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  vm-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3

      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v13

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Run NixOS VM tests
        run: |
          # Run integration tests in VMs
          nix build .#checks.x86_64-linux.vm-test --print-build-logs || true
          
          # Run specific service tests
          if [ -d "tests" ]; then
            for test in tests/*.nix; do
              echo "Running test: $test"
              nix build --file "$test" --print-build-logs || echo "Test $test failed"
            done
          fi

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ github.run_number }}
          path: |
            result*/
            tests/logs/
          retention-days: 7
